version: "3.9"

services:
  app:
    container_name: backend-proving-ground-2
    image: backend-proving-ground-2
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "${PORT}:${PORT}"
