version: "3.9"

services:
  tasks_db:
    container_name: "${DB_CONTAINER_NAME}"
    image: postgres
    networks:
      - tasks_net
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

  app:
    container_name: tasks_api
    image: backend-proving-ground-2
    restart: "no"
    networks:
      - tasks_net
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      ACCESS_TOKEN_SECRET: "${ACCESS_TOKEN_SECRET}"
      REFRESH_TOKEN_SECRET: "${REFRESH_TOKEN_SECRET}"
      PORT: "${PORT}"

    depends_on:
      - tasks_db

networks:
  tasks_net:
    driver: bridge
